// .lorien/types/services.d.ts (auto-generated by @darrylondil/lorien-build, do not edit)
// v1.0: all services typed as `unknown`. Refine manually or upgrade to v1.1 for TS-compiler inference.

declare module "@darrylondil/lorien-runtime" {
  interface Services {
    db: unknown // TODO: refine this type
  }
}

export {}
