// .Lorien/types/services.d.ts (auto-generated by @Lorien/build, do not edit)
// v1.0: all services typed as `unknown`. Refine manually or upgrade to v1.1 for TS-compiler inference.

declare module "@Lorien/runtime" {
  interface Services {
    db: unknown; // TODO: refine this type
  }
}

export {};
