// .lorien/types/providers.d.ts (auto-generated by @darrylondil/lorien-build, do not edit)
import type { ProvidedValue } from "@darrylondil/lorien-runtime"

declare module "@darrylondil/lorien-runtime" {
  interface Services {
    db: ProvidedValue<typeof import("../../providers/db.js").default>
    logger: ProvidedValue<typeof import("../../providers/logger.js").default>
  }
}
