export const VERSION = "0.0.0"
export type { ConvertOptions, ConvertResult, GeneratedFile } from "./convert.js"
export { convertOpenApiSpec } from "./convert.js"
export { emitClientHelper } from "./emit-client.js"
export type { EmitResult } from "./emit-operation.js"
export { emitOperationNode, OPENAPI_GENERATED_MARKER } from "./emit-operation.js"
export type { OpenAPIObject } from "./load-spec.js"
export { loadOpenApiSpec, OpenAPIError, validateOpenApi } from "./load-spec.js"
export { resolveRef } from "./resolve-ref.js"
export type { ConvertContext } from "./schema-to-zod.js"
export { newContext, schemaToZod } from "./schema-to-zod.js"
export { apiSlugFromSpec, kebabCase, operationFileName } from "./slug.js"
export type { WriteOptions, WriteResult } from "./write-files.js"
export { writeGeneratedFiles } from "./write-files.js"
