import { expectTypeOf, test } from "vitest"
import type { z } from "zod"
import type { Node, ServiceContext, Services, Trigger, WorkflowConfig } from "./types.js"

test("Node has required fields", () => {
  type N = Node<z.ZodObject<{ a: z.ZodString }>, z.ZodObject<{ b: z.ZodNumber }>>
  expectTypeOf<N>().toHaveProperty("inputs")
  expectTypeOf<N>().toHaveProperty("outputs")
  expectTypeOf<N>().toHaveProperty("run")
})

test("Trigger has no inputs, no run", () => {
  type T = Trigger<z.ZodObject<{ a: z.ZodString }>>
  expectTypeOf<T>().toHaveProperty("outputs")
  // @ts-expect-error -- triggers should not declare inputs
  expectTypeOf<T>().toHaveProperty("inputs")
})

test("Services interface exists and supports augmentation", () => {
  // The base interface is empty; users add fields via declaration merging
  // (.cozy/types/services.d.ts generated by @cozy/build). Verify that
  // augmentation produces a structurally-typed object.
  type Augmented = Services & { db: string }
  expectTypeOf<Augmented>().toHaveProperty("db")
})

test("ServiceContext has requestId and timestamp", () => {
  expectTypeOf<ServiceContext>().toEqualTypeOf<{ requestId: string; timestamp: number }>()
})

test("WorkflowConfig has services and target", () => {
  expectTypeOf<WorkflowConfig>().toHaveProperty("services")
  expectTypeOf<WorkflowConfig>().toHaveProperty("target")
})

test("Node run config is typed from the config schema when provided", () => {
  type N = Node<
    z.ZodObject<{ a: z.ZodString }>,
    z.ZodObject<{ b: z.ZodNumber }>,
    z.ZodObject<{ port: z.ZodNumber }>
  >
  type Config = Parameters<N["run"]>[2]
  expectTypeOf<Config>().toEqualTypeOf<{ port: number }>()
})

test("Node run config is undefined when no config schema is provided", () => {
  type N = Node<z.ZodObject<{ a: z.ZodString }>, z.ZodObject<{ b: z.ZodNumber }>>
  type Config = Parameters<N["run"]>[2]
  expectTypeOf<Config>().toEqualTypeOf<undefined>()
})
