import type { z } from "zod"

/**
 * Everything injected into nodes and middleware, by name. Augmented by the
 * generated `.lorien/types/providers.d.ts`, which types each entry from its
 * `providers/<name>.ts` file. Must remain an interface (not a type alias) to
 * support declaration merging.
 *
 * @example
 * // .lorien/types/providers.d.ts (auto-generated by @darrylondil/lorien-build):
 * declare module "@darrylondil/lorien-runtime" {
 *   interface Services {
 *     db: ProvidedValue<typeof import("../../providers/db.js").default>
 *   }
 * }
 */
// biome-ignore lint/suspicious/noEmptyInterface: intentional — users augment via declaration merging
export interface Services {}

/** What a node's `run` receives as its second argument. */
export type Providers = Services

/** Stand-in providers for tests: any subset, each with any subset of its members. */
export type MockProviders = { [K in keyof Services]?: Partial<Services[K]> }

export interface ServiceContext {
  requestId: string
  timestamp: number
}

export type ServiceValue<T = unknown> = T | ((ctx: ServiceContext) => T | Promise<T>)

export interface Disposable {
  dispose?(): void | Promise<void>
}

export interface WorkflowConfig {
  target: "hono"
  /** @deprecated Put each service in `providers/<name>.ts` with `defineProvider`. */
  services?: Record<string, ServiceValue<unknown>>
}

export type ZodObjectAny = z.ZodObject<z.ZodRawShape>

/**
 * Tailwind v3/v4 palette names. The IDE resolves these to the 500-weight hex
 * value at render time. Constrained to a literal union so editors offer
 * typeahead in `defineNode({ color: ... })`.
 */
export type TailwindColor =
  | "slate"
  | "gray"
  | "zinc"
  | "neutral"
  | "stone"
  | "red"
  | "orange"
  | "amber"
  | "yellow"
  | "lime"
  | "green"
  | "emerald"
  | "teal"
  | "cyan"
  | "sky"
  | "blue"
  | "indigo"
  | "violet"
  | "purple"
  | "fuchsia"
  | "pink"
  | "rose"

export interface Node<
  I extends ZodObjectAny = ZodObjectAny,
  O extends ZodObjectAny = ZodObjectAny,
  C extends ZodObjectAny | undefined = undefined,
> {
  readonly kind: "node"
  readonly name?: string
  readonly inputs: I
  readonly outputs: O
  readonly config?: C
  /** Optional Tailwind accent color, surfaced as a stripe in the IDE. */
  readonly color?: TailwindColor
  run(
    input: z.infer<I>,
    providers: Providers,
    config: C extends ZodObjectAny ? z.infer<C> : undefined,
  ): Promise<z.infer<O>>
}

export interface Trigger<
  O extends ZodObjectAny = ZodObjectAny,
  C extends ZodObjectAny | undefined = undefined,
> {
  readonly kind: "trigger"
  readonly name?: string
  readonly outputs: O
  readonly config?: C
}

export type AnyNodeOrTrigger =
  | Node<ZodObjectAny, ZodObjectAny, ZodObjectAny | undefined>
  | Trigger<ZodObjectAny, ZodObjectAny | undefined>
