import type { z } from "zod";

/**
 * Augmentable interface populated by the IDE's type generator from lorien.config.ts.
 * Users never write this themselves; .lorien/types/services.d.ts declares it.
 * Must remain an interface (not a type alias) to support declaration merging.
 *
 * @example
 * // .lorien/types/services.d.ts (auto-generated by @darrylondil/lorien-build, or write by hand):
 * declare module "@darrylondil/lorien-runtime" {
 *   interface Services {
 *     db: import("../services/db.js").Database
 *   }
 * }
 */
// biome-ignore lint/suspicious/noEmptyInterface: intentional — users augment via declaration merging
export interface Services {}

export interface ServiceContext {
  requestId: string;
  timestamp: number;
}

export type ServiceValue<T = unknown> =
  | T
  | ((ctx: ServiceContext) => T | Promise<T>);

export interface Disposable {
  dispose?(): void | Promise<void>;
}

export interface WorkflowConfig {
  target: "hono";
  services: Record<string, ServiceValue<unknown>>;
}

export type ZodObjectAny = z.ZodObject<z.ZodRawShape>;

/**
 * Tailwind v3/v4 palette names. The IDE resolves these to the 500-weight hex
 * value at render time. Constrained to a literal union so editors offer
 * typeahead in `defineNode({ color: ... })`.
 */
export type TailwindColor =
  | "slate" | "gray" | "zinc" | "neutral" | "stone"
  | "red" | "orange" | "amber" | "yellow" | "lime" | "green" | "emerald"
  | "teal" | "cyan" | "sky" | "blue" | "indigo" | "violet" | "purple"
  | "fuchsia" | "pink" | "rose";

export interface Node<
  I extends ZodObjectAny = ZodObjectAny,
  O extends ZodObjectAny = ZodObjectAny,
  C extends ZodObjectAny | undefined = undefined,
> {
  readonly kind: "node";
  readonly name?: string;
  readonly inputs: I;
  readonly outputs: O;
  readonly config?: C;
  /** Optional Tailwind accent color, surfaced as a stripe in the IDE. */
  readonly color?: TailwindColor;
  run(
    input: z.infer<I>,
    services: Services,
    config: C extends ZodObjectAny ? z.infer<C> : undefined,
  ): Promise<z.infer<O>>;
}

export interface Trigger<
  O extends ZodObjectAny = ZodObjectAny,
  C extends ZodObjectAny | undefined = undefined,
> {
  readonly kind: "trigger";
  readonly name?: string;
  readonly outputs: O;
  readonly config?: C;
}

export type AnyNodeOrTrigger =
  | Node<ZodObjectAny, ZodObjectAny, ZodObjectAny | undefined>
  | Trigger<ZodObjectAny, ZodObjectAny | undefined>;
